#!/usr/bin/env node
// G8 交付摘要的纯数据变换与渲染层：改动按模块聚合、gate PASS 历史、生效豁免、功能清单三态计数、
// 协作悬空项、severity 分桶，以及机器段 markdown 渲染。全纯函数，--self-test 直测（被 check-doc-budget 驱动）。

import { sep } from 'node:path'
import { openBlockers } from './blockers.mjs'

const GATES = ['G0', 'G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8']

export function splitLines(value) {
  return value ? value.split('\n').map((line) => line.trim()).filter(Boolean) : []
}

export function toPosix(value) {
  return value.split(sep).join('/')
}

// 交付摘要的「改动」段按模块聚合：逐个文件列 60 行没人读，模块 + 计数才能一眼看出爆炸半径。
export function groupByModule(files) {
  const groups = new Map()
  for (const file of files) {
    const parts = file.split('/')
    // apps/web/src/apps/Prediction/x.tsx → apps/web/src/apps/Prediction；深度不足时退到父目录。
    const key = parts.length > 5 ? parts.slice(0, 5).join('/') : parts.slice(0, Math.max(1, parts.length - 1)).join('/')
    groups.set(key, (groups.get(key) || 0) + 1)
  }
  return [...groups.entries()]
    .map(([module, count]) => ({ module, count }))
    .sort((a, b) => b.count - a.count || a.module.localeCompare(b.module))
}

// gate-history 是 append-only 的成功记录：每个阶段取最后一次 PASS，没有就是「无 PASS 历史」。
export function latestPassByGate(history) {
  const runs = Array.isArray(history?.runs) ? history.runs : []
  const latest = {}
  for (const run of runs) {
    if (!run?.gate || run.ok !== true) continue
    const previous = latest[run.gate]
    if (!previous || String(run.generatedAt) > String(previous.generatedAt)) latest[run.gate] = run
  }
  return latest
}

// 未过期豁免才算「仍待确认」；已过期的豁免不再生效，属于历史噪音，不进交付摘要。
export function activeWaivers(waiverFile, today) {
  const entries = Array.isArray(waiverFile?.waivers) ? waiverFile.waivers : Array.isArray(waiverFile) ? waiverFile : []
  return entries.filter((entry) => {
    if (!entry?.ruleId) return false
    if (!entry.expiresAt) return true
    return String(entry.expiresAt) >= today
  })
}

export function parseInventoryCounts(text) {
  const counts = { 做: 0, 不做: 0, 延期: 0 }
  for (const match of text.matchAll(/本期\s*[:：=]?\s*(做|不做|延期)/g)) counts[match[1]] += 1
  // 表格形态：`| F01 | ... | 做 | ...`，只认独立单元格，避免命中「不做的原因」这类叙述。
  for (const match of text.matchAll(/\|\s*(做|不做|延期)\s*\|/g)) counts[match[1]] += 1
  return counts
}

// 「待修复 / 未处理」是协作文档里的悬空项标记，G6 要求清零或转豁免，G8 必须如实列出来。
export function openCollaborationItems(text) {
  return splitLines(text)
    .filter((line) => /待修复|未处理|待确认/.test(line) && line.startsWith('|'))
    .map((line) => line.replace(/\s+/g, ' ').slice(0, 160))
}

export function severityBuckets(checks) {
  const list = Array.isArray(checks) ? checks : []
  return {
    fail: list.filter((check) => !check.ok && check.severity === 'error'),
    warn: list.filter((check) => !check.ok && check.severity === 'warn'),
    waived: list.filter((check) => !check.ok && check.severity === 'waived'),
  }
}

export function renderSummary(facts) {
  const gateRows = GATES.map((gate) => {
    const pass = facts.gatePasses[gate]
    return `| ${gate} | ${pass ? 'PASS' : '—'} | ${pass ? pass.generatedAt.slice(0, 19).replace('T', ' ') : '无 PASS 历史'} | ${pass?.evidence || '—'} |`
  }).join('\n')

  const commandRows = facts.commands.length
    ? facts.commands.map((item) => `| \`${item.label}\` | exit=${item.status ?? 'null'} | ${item.ok ? 'PASS' : 'FAIL'} |`).join('\n')
    : '| 无 | | |'

  const moduleRows = facts.modules.length
    ? facts.modules.map((item) => `| ${item.module} | ${item.count} |`).join('\n')
    : '| 无改动文件（base 不可解析或工作区干净） | 0 |'

  const waiverRows = facts.waivers.length
    ? facts.waivers.map((item) => `| ${item.ruleId} | ${item.owner || '未登记'} | ${item.expiresAt || '无期限'} | ${(item.reason || '').replace(/\|/g, '/').slice(0, 120)} |`).join('\n')
    : '| 无 | | | |'

  const warnRows = facts.warn.length
    ? facts.warn.map((item) => `| ${item.ruleId} | ${(item.message || '').replace(/\|/g, '/').replace(/\n/g, ' ').slice(0, 160)} |`).join('\n')
    : '| 无 | |'

  const mockRows = facts.mockResidue.map((item) => `| \`${item.pattern}\` | ${item.tool === 'rg' ? item.hits : item.tool} | ${item.files.join('<br>') || '—'} |`).join('\n')

  const cell = (value) => String(value ?? '').replace(/\|/g, '/').replace(/\n/g, ' ').slice(0, 160)
  const blockerRows = facts.openBlockers.length
    ? facts.openBlockers.map((item) => `| ${item.id} | ${item.owner} | ${item.blocksGate || '—'} | ${cell(item.summary)} |`).join('\n')
    : '| 无 | | | |'
  const changeRows = facts.openChanges.length
    ? facts.openChanges.map((item) => `| ${item.id} | ${item.owner} | ${item.blocksGate || '—'} | ${cell(item.summary)} |`).join('\n')
    : '| 无 | | | |'

  return `<!-- GENERATED by common/engine/agent-scripts/render-delivery-summary.mjs；机器段落勿手改，人工内容只写占位处 -->
# 交付摘要（机器段） — ${facts.projectId}

- 生成时间：${facts.generatedAt}
- 最近一次 gate：${facts.latestGate} → ${facts.latestGateOk ? 'PASS' : 'BLOCKED'}（${facts.latestGateAt || '未生成'}）
- 基线：\`${facts.baseRef}\`${facts.baseResolvable ? '' : '（不可解析，改动集仅含本地未提交部分）'}

## 1. 改动

共 ${facts.changedFileCount} 个文件：

| 模块 | 文件数 |
|------|--------|
${moduleRows}

## 2. 验证

阶段 PASS 历史（来自 append-only \`agent/gate-history.json\`）：

| 门禁 | 结论 | 时间 | 证据 |
|------|------|------|------|
${gateRows}

最近一次 gate 实际执行的命令（退出码来自真实子进程）：

| 命令 | 退出码 | 结论 |
|------|--------|------|
${commandRows}

机器事实层（biome / tsc / vitest）：${facts.buildQuality}

## 3. 功能清单

做 ${facts.inventory.做} / 不做 ${facts.inventory.不做} / 延期 ${facts.inventory.延期}（来源 \`product/00-feature-inventory.md\`${facts.inventoryFound ? '' : '，**文件缺失**'}）

## 4. 待确认（机器线索）

未解除的阻塞（来自结构化单一源 \`agent/blockers.json\`，非散文）：

| ID | Owner | 卡在 | 摘要 |
|----|-------|------|------|
${blockerRows}

未收口的需求变更（相对 PRD 的 delta，同源）：

| ID | Owner | 需在 | 摘要 |
|----|-------|------|------|
${changeRows}

生效中的规则豁免：

| Rule ID | Owner | 到期 | 理由 |
|---------|-------|------|------|
${waiverRows}

- 责任模块残留 \`// ASSUMED:\` 占位：${facts.assumedHits} 处${facts.assumedFiles.length ? `（${facts.assumedFiles.join('、')}）` : ''}
- \`06-collaboration.md\` 悬空项（含「待修复/未处理/待确认」的表格行，**散文线索非真值，以 \`blockers.json\` 为准**）：${facts.openItems.length} 条
${facts.openItems.length ? facts.openItems.map((line) => `  - ${line}`).join('\n') : '  - 无'}

<!-- 人工补充：产品/设计/后端/QA 仍需拍板的问题，机器判不了的写在这里 -->

## 5. 残留风险（机器线索）

未解除阻塞（同 §4，此处提示上线风险）：${facts.openBlockers.length ? facts.openBlockers.map((item) => `${item.id}(${item.category})`).join('、') : '无'}

Warn 级 findings（不阻断，但属于已知欠账）：

| Rule ID | Message |
|---------|---------|
${warnRows}

Mock 残留 grep：

| 模式 | 命中文件数 | 文件（最多 10 个） |
|------|-----------|-------------------|
${mockRows}

<!-- 人工补充：未覆盖场景、已知问题、上线注意事项 -->
`
}

export function selfTest() {
  const cases = []
  const record = (name, condition) => {
    cases.push(name)
    if (!condition) {
      console.error(`self-test failed: ${name}`)
      process.exit(1)
    }
  }

  const groups = groupByModule([
    'apps/web/src/apps/Prediction/index.tsx',
    'apps/web/src/apps/Prediction/List.tsx',
    'apps/web/src/services/api/prediction.ts',
    'package.json',
  ])
  record('groupByModule 按模块聚合并按文件数降序', groups[0].module === 'apps/web/src/apps/Prediction' && groups[0].count === 2)
  record('groupByModule 顶层文件不崩', groups.some((item) => item.module === 'package.json' || item.module === ''))

  const passes = latestPassByGate({
    runs: [
      { gate: 'G5', ok: true, generatedAt: '2026-07-01T00:00:00.000Z', evidence: 'a' },
      { gate: 'G5', ok: true, generatedAt: '2026-07-02T00:00:00.000Z', evidence: 'b' },
      { gate: 'G6', ok: false, generatedAt: '2026-07-03T00:00:00.000Z', evidence: 'c' },
    ],
  })
  record('latestPassByGate 取最后一次 PASS', passes.G5?.evidence === 'b')
  record('latestPassByGate 不把 BLOCK 当 PASS', passes.G6 === undefined)

  const waivers = activeWaivers({ waivers: [{ ruleId: 'A', expiresAt: '2026-01-01' }, { ruleId: 'B', expiresAt: '2099-01-01' }, { ruleId: 'C' }] }, '2026-08-03')
  record('activeWaivers 过滤已过期豁免', waivers.length === 2 && !waivers.some((item) => item.ruleId === 'A'))

  const counts = parseInventoryCounts('| F01 | 标题 | 做 |\n本期：不做\n| F02 | 标题 | 延期 |\n这条不做的原因是范围外')
  record('parseInventoryCounts 统计三态', counts.做 === 1 && counts.不做 === 1 && counts.延期 === 1)

  const open = openCollaborationItems('| B10 | 格式 | 待修复 |\n正文里提到待修复但不是表格行\n| B11 | ok | 已修 |')
  record('openCollaborationItems 只认表格行', open.length === 1)

  const reg = openBlockers([
    { id: 'BLK-1', type: 'blocker', status: 'open', owner: 'be', blocksGate: 'G6', summary: '错误码待后端销账' },
    { id: 'CHG-1', type: 'change', status: 'open', owner: 'pm', summary: '杠杆改 1-20x 硬限制' },
    { id: 'BLK-2', type: 'blocker', status: 'resolved', owner: 'be', resolution: 'x', resolvedAt: '2026-08-03', summary: 'done' },
  ])
  record('openBlockers 分组且丢弃 resolved', reg.blockers.length === 1 && reg.changes.length === 1)

  const buckets = severityBuckets([
    { ruleId: 'X', ok: false, severity: 'error' },
    { ruleId: 'Y', ok: false, severity: 'warn' },
    { ruleId: 'Z', ok: true, severity: 'error' },
  ])
  record('severityBuckets 不把 ok=true 算失败', buckets.fail.length === 1 && buckets.warn.length === 1)

  const text = renderSummary({
    projectId: 'PR-00001',
    generatedAt: '2026-08-03T00:00:00.000Z',
    baseRef: 'origin/online',
    baseResolvable: true,
    latestGate: 'G8',
    latestGateOk: true,
    latestGateAt: '2026-08-03T00:00:00.000Z',
    changedFileCount: 2,
    modules: groups,
    gatePasses: passes,
    commands: [{ label: 'verify-build-quality --project PR-00001', status: 0, ok: true }],
    buildQuality: 'PASS（5 条结论）',
    inventory: counts,
    inventoryFound: true,
    waivers,
    assumedHits: 0,
    assumedFiles: [],
    openBlockers: reg.blockers,
    openChanges: reg.changes,
    openItems: open,
    warn: buckets.warn,
    mockResidue: [{ pattern: '@mock-only', hits: 0, tool: 'rg', files: [] }],
  })
  for (const section of ['## 1. 改动', '## 2. 验证', '## 3. 功能清单', '## 4. 待确认', '## 5. 残留风险', 'GENERATED by']) {
    record(`renderSummary 含 ${section}`, text.includes(section))
  }
  record('renderSummary 渲染结构化阻塞而非只 grep', text.includes('BLK-1') && text.includes('CHG-1') && text.includes('agent/blockers.json'))
  record('renderSummary 保留人工占位', text.split('<!-- 人工补充').length === 3)

  console.log(`PASS render-delivery-summary self-test (${cases.length} cases)`)
}

if (process.argv[1] && process.argv[1].endsWith('delivery-summary.mjs') && process.argv.includes('--self-test')) {
  selfTest()
  process.exit(0)
}
