#!/usr/bin/env node
// Pi 适配器：生成 Pi coding-agent 的规则强制扩展（tool_call -> 规则注入 / tool_result -> 代码门禁）。
//
// Pi 与 Codex/Claude 同为直连交互式 agent，但用「extension」而非 hooks.json/settings.json 布线。
// 全局 `~/.pi/agent/AGENTS.md` 已软链到共享 L1 AGENT.md（同时充当 L1 与 adapter，含执行协议），
// 因此 Pi 只需再装一个扩展把每次编辑桥接到既有的 Claude 形状 hook 脚本，复用同一套 L2 注入/门禁逻辑。
//
// doctor 只静态校验扩展是否装好且含关键桥接标记（与 CODEX-HOOK 解析 hooks.json 命令串同一取证标准），
// 不依赖 Pi 实时运行——扩展必须「构造即正确」。

import assert from 'node:assert/strict'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// 相对 `~/.pi/agent/` 的扩展安装路径；Pi 从 `~/.pi/agent/extensions/` 自动发现。
export const PI_EXTENSION_RELPATH = 'extensions/docs-tdd-rules.ts'

// doctor 用来证明扩展确实把两端桥接到共享脚本的标记（缺任一即判扩展未正确布线）。
export const PI_EXTENSION_MARKERS = Object.freeze([
  'rule-context-hook.mjs',
  'claude-posttooluse-gate.mjs',
  '--client pi',
  'before_agent_start',
  'tool_call',
  'tool_result',
])

/**
 * 生成 Pi 规则强制扩展的 TypeScript 源码。
 * @param {{ docsSystemRoot: string }} params docsSystemRoot 用于把 hook 脚本写成绝对路径，物理搬迁只改一处。
 */
export function createPiExtension({ docsSystemRoot }) {
  if (typeof docsSystemRoot !== 'string' || !docsSystemRoot.trim()) throw new Error('docsSystemRoot is required')
  const ruleHook = `${docsSystemRoot}/common/engine/agent-scripts/rule-context-hook.mjs`
  const gateScript = `${docsSystemRoot}/common/engine/agent-scripts/claude-posttooluse-gate.mjs`
  return `// AUTO-GENERATED by install-local-agent-rules.mjs — do not edit by hand.
// Pi rule-enforcement extension: injects L2 context in before_agent_start (the last point
// that can add an LLM-visible message), then bridges tool events to the shared receipt/code gate.
// Writes fail closed when the preflight hook did not complete, because tool_call cannot add
// context to the model request that already happened.
import { spawnSync } from "node:child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const RULE_HOOK = ${JSON.stringify(ruleHook)};
const GATE_SCRIPT = ${JSON.stringify(gateScript)};
// docs-tdd rule consumer identity: --client pi
const CLIENT_ARGS = ["--client", "pi"];
const WRITE_TOOLS = new Set(["edit", "write", "multiedit", "notebookedit", "apply_patch", "bash", "powershell"]);
let preflightReady = false;

function sessionId(ctx: { sessionManager: { getSessionFile(): string | undefined } }): string {
  return process.env.PI_SESSION_ID || ctx.sessionManager.getSessionFile() || "pi-session";
}

function runHook(script: string, payload: unknown, extraArgs: string[] = []): { ok: boolean; stdout: string } {
  try {
    const result = spawnSync("node", [script, ...extraArgs], {
      input: JSON.stringify(payload),
      encoding: "utf8",
      timeout: 20000,
    });
    return { ok: result.status === 0, stdout: result.stdout || "" };
  } catch {
    return { ok: false, stdout: "" };
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("session_start", async (_event, ctx) => {
    preflightReady = false;
    runHook(RULE_HOOK, {
      hook_event_name: "SessionStart",
      session_id: sessionId(ctx),
      cwd: ctx.cwd,
    }, CLIENT_ARGS);
  });

  pi.on("before_agent_start", async (_event, ctx) => {
    preflightReady = false;
    const { ok, stdout } = runHook(RULE_HOOK, {
      hook_event_name: "BeforeAgentStart",
      session_id: sessionId(ctx),
      cwd: ctx.cwd,
    }, CLIENT_ARGS);
    if (!ok || !stdout.trim()) return;
    let parsed: { hookSpecificOutput?: { additionalContext?: string } };
    try {
      parsed = JSON.parse(stdout);
    } catch {
      return;
    }
    preflightReady = true;
    const context = parsed.hookSpecificOutput?.additionalContext;
    if (!context) return;
    return {
      message: {
        customType: "docs-tdd-rule-context",
        content: context,
        display: false,
      },
    };
  });

  pi.on("session_compact", async (_event, ctx) => {
    preflightReady = false;
    runHook(RULE_HOOK, {
      hook_event_name: "PreCompact",
      session_id: sessionId(ctx),
      cwd: ctx.cwd,
    }, CLIENT_ARGS);
  });

  pi.on("tool_call", async (event, ctx) => {
    const toolName = String(event.toolName || "").toLowerCase();
    if (!WRITE_TOOLS.has(toolName)) return;
    if (!preflightReady) return { block: true, reason: "docs_tdd L2 preflight did not complete before this turn. Retry the user turn or reload the extension." };
    const payload = {
      hook_event_name: "PreToolUse",
      session_id: sessionId(ctx),
      cwd: ctx.cwd,
      tool_use_id: (event as { toolCallId?: string }).toolCallId ?? "",
      tool_name: event.toolName,
      tool_input: event.input ?? {},
    };
    const { ok, stdout } = runHook(RULE_HOOK, payload, CLIENT_ARGS);
    if (!ok) return { block: true, reason: "docs_tdd L2 rule hook failed before this write." };
    if (!stdout.trim()) return;
    let parsed: { hookSpecificOutput?: { permissionDecision?: string; permissionDecisionReason?: string; additionalContext?: string } };
    try {
      parsed = JSON.parse(stdout);
    } catch {
      return;
    }
    const out = parsed.hookSpecificOutput;
    if (!out) return;
    if (out.permissionDecision === "deny") {
      return { block: true, reason: out.permissionDecisionReason || "docs_tdd L2 rules require re-reading injected context before this edit." };
    }
    if (out.additionalContext) {
      return { block: true, reason: "docs_tdd discovered rule context after Pi's preflight window. Retry the user turn so the context is visible before editing." };
    }
  });

  pi.on("tool_result", async (event, ctx) => {
    const toolName = String((event as { toolName?: string }).toolName || "").toLowerCase();
    if (!WRITE_TOOLS.has(toolName)) return;
    const payload = {
      hook_event_name: "PostToolUse",
      session_id: sessionId(ctx),
      cwd: ctx.cwd,
      tool_use_id: (event as { toolCallId?: string }).toolCallId ?? "",
      tool_name: (event as { toolName?: string }).toolName ?? "",
    };
    // Record the post-edit receipt through the same shared hook, then run the code gate.
    runHook(RULE_HOOK, payload, CLIENT_ARGS);
    const gate = runHook(GATE_SCRIPT, payload);
    if (!gate.ok && gate.stdout.trim()) {
      try {
        ctx.ui.notify("docs_tdd code gate flagged this edit — run 'docs-tdd changed' before continuing.", "warn");
      } catch {
        // notify is best-effort
      }
    }
  });
}
`
}

function selfTest() {
  const ext = createPiExtension({ docsSystemRoot: '/docs' })
  for (const marker of PI_EXTENSION_MARKERS) assert.ok(ext.includes(marker), `pi extension must contain marker: ${marker}`)
  assert.ok(ext.includes('/docs/common/engine/agent-scripts/rule-context-hook.mjs'), 'absolute rule hook path')
  assert.ok(ext.includes('/docs/common/engine/agent-scripts/claude-posttooluse-gate.mjs'), 'absolute gate path')
  assert.ok(ext.includes('pi.on("before_agent_start"'), 'injects context before the agent turn')
  assert.ok(ext.includes('customType: "docs-tdd-rule-context"'), 'returns an LLM-visible preflight message')
  assert.ok(ext.includes('pi.on("tool_call"'), 'wires tool_call')
  assert.ok(ext.includes('pi.on("tool_result"'), 'wires tool_result')
  assert.throws(() => createPiExtension({}), /docsSystemRoot is required/)
  assert.equal(PI_EXTENSION_RELPATH, 'extensions/docs-tdd-rules.ts')
  console.log('pi-adapter self-test passed.')
}

if (process.argv.includes('--self-test') && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) selfTest()
