#!/usr/bin/env node
// PROJECTS.md 索引的纯解析与渲染层：README 状态解析（机器行 > frontmatter > 叙述行的优先级）、
// legacy/对账标记、markdown 表渲染。全纯函数，--self-test 直测（被 check-doc-budget 驱动）。

import assert from 'node:assert/strict'

export function firstMatch(text, patterns, fallback = '') {
  for (const pattern of patterns) {
    const match = pattern.exec(text)
    if (match?.[1]) return match[1].trim()
  }
  return fallback
}

export function stripMd(value) {
  return value
    .replace(/^#+\s*/, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/\s+/g, ' ')
    .trim()
}

// 解析 README 顶部的 YAML frontmatter，返回对象。只处理简单标量（字符串/布尔/数字），不引入外部 YAML 依赖。
export function parseFrontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n?/)
  if (!match) return {}
  const result = {}
  for (const line of match[1].split('\n')) {
    const colonIndex = line.indexOf(':')
    if (colonIndex === -1) continue
    const key = line.slice(0, colonIndex).trim()
    let value = line.slice(colonIndex + 1).trim()
    let quoted = false
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
      quoted = true
    }
    if (value === 'true') result[key] = true
    else if (value === 'false') result[key] = false
    else if (!quoted && /^\d+$/.test(value)) result[key] = Number(value)
    else result[key] = value
  }
  return result
}

export function frontmatterStatus(readme) {
  const fm = parseFrontmatter(readme)
  // 已关闭项目的生命周期状态优先于历史阶段，否则 PROJECTS.md 会把已归档项目误显示为活跃 G8。
  // stage 仅保留为 frontmatter 兼容字段，不在索引中展示，避免把上线归档误读为补跑过同名 Gate。
  if (fm.status && fm.status !== 'active') return `${fm.status}`
  if (fm.stage) return `${fm.stage}`
  return ''
}

// 只取表格机器行「最新通过门禁」。它是 set-project-stage.mjs 的唯一写真值，优先级高于 frontmatter。
export function machineRowStatus(readme) {
  return stripMd(firstMatch(readme, [/\|\s*(?:\*\*)?最新通过门禁(?:\*\*)?\s*\|\s*([^|]+)\|/], ''))
}

// README 状态解析：机器行「最新通过门禁」优先（gate 通过时脚本写入，客观真值）；人工叙述行只做回落。
export function parseStatus(readme) {
  return stripMd(firstMatch(readme, [
    /\|\s*(?:\*\*)?最新通过门禁(?:\*\*)?\s*\|\s*([^|]+)\|/,
    /^>\s*\*\*状态\*\*[:：]\s*(.+)$/m,
    /^>\s*状态[:：]\s*(.+)$/m,
    /\|\s*(?:\*\*)?当前阶段(?:\*\*)?\s*\|\s*([^|]+)\|/,
    /\|\s*(?:\*\*)?代码实现(?:\*\*)?\s*\|\s*([^|]+)\|/,
  ], '未记录'))
}

// 阶段真值分级：README 声称的 stage 若没有同阶段真实 PASS 历史就打标，避免「自己写上去的阶段」
// 和「机器背书的阶段」在索引里长得一样。G5+ 沿用历史标记 legacy-unverified（多为机制上线前的旧项目），
// G2-G4 用 self-declared（gate 早已可跑，没跑就是没跑）。G0/G1 不打标：按 workflow-gates，
// 项目 gate 从 G2 起才要求逐阶段跑，G0/G1 本就没有「应存在的 PASS」。
const SELF_DECLARED_STAGES = ['G2', 'G3', 'G4']

export function legacyAwareStatus(status, history, evidenceExists) {
  const stage = String(status || '').match(/\b(G[2-8])\b/)?.[1]
  if (!stage) return status
  const marker = SELF_DECLARED_STAGES.includes(stage) ? 'self-declared' : 'legacy-unverified'
  if (String(status).includes(marker)) return status
  const verified = Array.isArray(history?.runs) && history.runs.some((run) => (
    run?.gate === stage
    && run?.ok === true
    && run?.summary?.fail === 0
    && typeof run?.evidence === 'string'
    && evidenceExists(run.evidence)
  ))
  return verified ? status : `${status} (${marker})`
}

// 若 G5 记为报告态 frontend-complete-pending-reconcile（前端完成、仅待真实字段对账），追加可读标记。
export function frontendReconcileNote(status, stageStatusJson) {
  const g5 = stageStatusJson?.stages?.G5?.status
  if (g5 !== 'frontend-complete-pending-reconcile') return status
  return String(status).includes('前端完成待对账') ? status : `${status} · 前端完成待对账`
}

function cell(value) {
  return String(value || '未记录').replace(/\|/g, '\\|').replace(/\n/g, '<br>')
}

function worktreeCell(project) {
  if (!project.worktree) return '—（无活跃 worktree）'
  return `\`${project.worktree}\``
}

export function renderMarkdown(projects, generatedAt) {
  const rows = projects.map((project) => `| [${cell(project.id)}](./prds/${cell(project.id)}/README.md) | ${cell(project.workflow || 'v1')} | ${cell(project.status)} | ${cell(project.g2)} | ${cell(project.gate)} | ${project.evidenceCount} | ${worktreeCell(project)} | ${cell(project.modulePath)} |`)
  return `# docs_tdd Project Index

> Generated by \`common/engine/agent-scripts/update-project-index.mjs --write\` at ${generatedAt}. Do not hand-edit table rows; update project README / product docs, then regenerate.
> 本表是「当前有哪些项目 / 状态 / 在哪个 worktree」的唯一生成式聚合视图，不是底层事实源。Worktree 列直接派生自 \`git worktree list\`，禁止手工登记；README / AGENTS / CONTEXT 只放指向本表的指针，不得再抄一份项目清单（\`check-doc-budget.mjs\` 会拦）。

## Active Projects

| Project | Workflow | Status | G2 / Scope approval | Latest gate / exit | Evidence files | Worktree | Responsibility modules |
|---------|----------|--------|---------------------|--------------------|----------------|----------|-------------------------|
${rows.join('\n')}

## Notes

- This index is a generated navigation view; its underlying facts remain in each project README / agent state and Git.
- Workflow 来自 README \`workflowVersion\`；缺字段的历史项目按 v1，存在 \`work-item.json\` 的项目按 v2。v2 状态来自完整性及当前代码指纹均有效的 enforced \`latest-result.json\`；v1 状态才读取 G Gate。
- 对 v1，project status 使用机器行 \`| 最新通过门禁 | GX |\`，再回落到 README frontmatter \`stage\` 和叙述行。G2+ 缺少同阶段成功历史与真实证据时标记 \`self-declared\`（G2-G4）或 \`legacy-unverified\`（G5+）。
- v1 的 \`self-declared\` 表示 README 声称到了 G2-G4，但 \`agent/gate-history.json\` 没有同阶段真实 PASS；应补跑 \`docs-tdd gate <PR> <Gx>\`，不是改 README。
- \`legacy-unverified\` = 机制上线（gate-history 机器背书）之前的自声明 G8/G5+，非机器背书。这些旧项目 worktree 多已回收、无真实 gate 运行；**不 backfill 伪造 PASS 历史**（违反"不伪造证据"原则）。要转为机器背书须有真实结构的 \`agent/gate-history.json\` 且其 evidence 路径真实存在。
- \`· 前端完成待对账\` = G5 记为报告态 \`frontend-complete-pending-reconcile\`：前端已交付、仅待后端真实字段对账；此态不放行 G6（见 \`workflow-gates.md\`）。
- v1 的 G2/module 来自 \`product/00-feature-inventory.md\`，最终 Gate 来自 \`agent/gate-results.json\`；v2 的 scope approval / exit 来自 \`work-item.json\` / \`latest-result.json\`。
- Worktree column is derived live from \`git worktree list\` (configured branch prefix or \`fix/<ID>\`); a project with no active worktree shows \`—\`.
- Regenerate after creating or materially updating a project: \`node apps/web/docs_tdd/common/engine/agent-scripts/update-project-index.mjs --write\`.
- README frontmatter schema is enforced by \`common/engine/schemas/project-frontmatter.schema.json\`; invalid frontmatter will be reported by \`check-doc-budget.mjs\`.
`
}

// CONTEXT.md 的「当前工作重点」此前是手写的，实际停在两个月前的项目上（PR-01685）。
// 焦点改为派生：取最近一次 v1 Gate 或 v2 verify 活动的项目，
// 在 PROJECTS.md 同一次 --write 里回写，手改会被下次重生成覆盖。
export function latestGateFocus(projects) {
  const dated = (projects || []).filter((project) => project?.gateAt)
  if (!dated.length) return null
  return dated.slice().sort((a, b) => String(b.gateAt).localeCompare(String(a.gateAt)))[0]
}

export const FOCUS_LINE_RE = /^- 当前工作重点：.*$/m

export function focusLine(project) {
  if (!project) return '- 当前工作重点：无 Gate / verify 活动记录（先按项目版本运行 `docs-tdd gate` 或 `docs-tdd verify`，再重生成本行）。'
  const worktree = project.worktree ? `，worktree \`${project.worktree}\`` : ''
  return `- 当前工作重点：**${project.title || project.id}**——最近工作流结果 ${project.gate}（${String(project.gateAt).slice(0, 10)}）${worktree}。本行由 \`update-project-index.mjs --write\` 从最近 Gate / verify 活动派生，勿手改。`
}

// 就地替换 CONTEXT.md 的焦点行。找不到该行时不猜位置（返回 matched:false 让调用方告警）。
export function replaceFocusLine(text, line) {
  if (!FOCUS_LINE_RE.test(text)) return { text, matched: false, changed: false }
  const next = text.replace(FOCUS_LINE_RE, line)
  return { text: next, matched: true, changed: next !== text }
}

export function selfTest() {
  const stripped = stripMd('`apps/web/docs_tdd/prds/PR-00001` **done**')
  assert.ok(stripped.includes('docs_tdd') && !stripped.includes('`') && !stripped.includes('**'), 'stripMd should preserve underscores and remove markdown markers')
  const markdown = renderMarkdown([
    { id: 'PR-00001', status: 'G6', g2: 'Aven / 2026-07-10', gate: 'G6 PASS (fail=0, warn=0)', evidenceCount: 1, worktree: '/Users/aven/github/PR-00001', modulePath: 'apps/web/src/apps/Demo' },
  ], '2026-01-01T00:00:00.000Z')
  assert.ok(markdown.includes('[PR-00001](./prds/PR-00001/README.md)') && markdown.includes('| Project | Workflow | Status |'), 'rendered markdown table is incomplete')
  assert.ok(markdown.includes('| Worktree |') && markdown.includes('/Users/aven/github/PR-00001'), 'worktree column missing from rendered table')
  const noWt = renderMarkdown([{ id: 'PR-00002', status: 'G2', g2: '—', gate: '未生成', evidenceCount: 0, worktree: '', modulePath: '—' }], '2026-01-01T00:00:00.000Z')
  assert.ok(noWt.includes('无活跃 worktree'), 'empty worktree should render placeholder')
  assert.equal(parseStatus('| 字段 | 值 |\n|------|-----|\n| 最新通过门禁 | G6 |\n| 当前阶段 | G0 资料接收 |'), 'G6', 'machine row must win over narrative 当前阶段')
  assert.equal(parseStatus('| 项 | 值 |\n|----|----|\n| **当前阶段** | **G4 开发中** |'), 'G4 开发中', 'bold 当前阶段 label should still parse')
  assert.equal(parseStatus('> **状态**: G5 联调中'), 'G5 联调中', 'quote-style status fallback broken')
  const fm = parseFrontmatter('---\nprojectId: PR-00003\nstage: G6\nstatus: active\n---\n# PR-00003')
  assert.ok(fm.projectId === 'PR-00003' && fm.stage === 'G6' && fm.status === 'active', 'parseFrontmatter should parse simple scalars')
  assert.equal(frontmatterStatus('---\nstage: G6\n---\n# PR-00003\n\n## 状态\n| 当前阶段 | G0 |'), 'G6', 'frontmatter stage must win over narrative status')
  assert.equal(frontmatterStatus('---\nstatus: closed\nstage: G8\n---\n# PR-00003'), 'closed', 'closed lifecycle status must not be hidden by or imply a historical stage')
  const prioritySample = '---\nstage: G4\n---\n# PR-00004\n\n## 状态\n\n| 字段 | 值 |\n|------|-----|\n| 最新通过门禁 | G6 |\n| 当前阶段 | G0 |'
  assert.equal(machineRowStatus(prioritySample) || frontmatterStatus(prioritySample) || parseStatus(prioritySample), 'G6', 'machine row must win over frontmatter stage')
  assert.equal(legacyAwareStatus('G8', { runs: [] }, () => false), 'G8 (legacy-unverified)', 'G5+ without machine history must be marked legacy-unverified')
  assert.equal(legacyAwareStatus('G8', { runs: [{ gate: 'G8', ok: true, summary: { fail: 0 }, evidence: 'evidence/gate/g8/README.md' }] }, () => true), 'G8', 'verified G8 should not carry legacy marker')
  assert.equal(legacyAwareStatus('G4 开发中', { runs: [] }, () => false), 'G4 开发中 (self-declared)', 'G2-G4 without machine history must be marked self-declared')
  assert.equal(legacyAwareStatus('G4', { runs: [{ gate: 'G4', ok: true, summary: { fail: 0 }, evidence: 'evidence/gate/g4/README.md' }] }, () => true), 'G4', 'verified G4 should carry no marker')
  assert.equal(legacyAwareStatus('G4', { runs: [{ gate: 'G4', ok: true, summary: { fail: 0 }, evidence: 'evidence/gate/g4/README.md' }] }, () => false), 'G4 (self-declared)', 'G4 history with missing evidence file must still be marked')
  assert.equal(legacyAwareStatus('G1 资料接收', { runs: [] }, () => false), 'G1 资料接收', 'G0/G1 have no expected PASS history and must stay unmarked')
  assert.equal(legacyAwareStatus('G4 (self-declared)', { runs: [] }, () => false), 'G4 (self-declared)', 'marker must not be appended twice')
  assert.equal(frontendReconcileNote('G4', { stages: { G5: { status: 'frontend-complete-pending-reconcile' } } }), 'G4 · 前端完成待对账', 'frontend-complete-pending-reconcile G5 should annotate status')
  assert.equal(frontendReconcileNote('G4', { stages: { G5: { status: 'blocked' } } }), 'G4', 'non-reconcile G5 status must not annotate')
  // CONTEXT.md 焦点行派生（B3：手写焦点会腐化）。
  const focusProjects = [
    { id: 'PR-00001', title: 'PR-00001 老项目', gate: 'G8 PASS (fail=0, warn=0)', gateAt: '2026-06-01T00:00:00.000Z', worktree: '' },
    { id: 'PR-00002', title: 'PR-00002 新项目', gate: 'G6 PASS (fail=0, warn=2)', gateAt: '2026-08-20T00:00:00.000Z', worktree: '/tmp/PR-00002' },
    { id: 'PR-00003', title: 'PR-00003 没跑过门禁', gate: '未生成', gateAt: '' },
  ]
  assert.equal(latestGateFocus(focusProjects).id, 'PR-00002', 'focus must be the most recent gate activity')
  assert.equal(latestGateFocus([{ id: 'PR-00003', gateAt: '' }]), null, 'no dated gate activity → no focus')
  const line = focusLine(latestGateFocus(focusProjects))
  assert.ok(line.startsWith('- 当前工作重点：') && line.includes('PR-00002') && line.includes('2026-08-20') && line.includes('/tmp/PR-00002'), `focus line malformed: ${line}`)
  assert.ok(focusLine(null).includes('无 Gate / verify 活动记录'), 'empty focus must say so instead of inventing one')
  const replaced = replaceFocusLine('# ctx\n\n- 主仓库路径：`/x`\n- 当前工作重点：推进 **PR-01685**——旧的。\n- 其他：y\n', line)
  assert.ok(replaced.matched && replaced.changed && replaced.text.includes('PR-00002') && !replaced.text.includes('PR-01685'), 'focus line replacement failed')
  assert.ok(replaced.text.includes('- 主仓库路径：`/x`') && replaced.text.includes('- 其他：y'), 'replacement must not touch sibling lines')
  assert.equal(replaceFocusLine('# ctx\n无焦点行\n', line).matched, false, 'missing focus line must报 matched:false，不猜位置')
  console.log('PASS project index renderer')
}

if (process.argv[1] && process.argv[1].endsWith('project-index.mjs') && process.argv.includes('--self-test')) {
  selfTest()
  process.exit(0)
}
