#!/usr/bin/env node
// PROJECTS.md 索引的纯解析与渲染层：README 状态解析（机器行 > frontmatter > 叙述行的优先级）、
// legacy/对账标记、markdown 表渲染。全纯函数，--self-test 直测（被 check-doc-budget 驱动）。

import assert from 'node:assert/strict'

export function firstMatch(text, patterns, fallback = '') {
  for (const pattern of patterns) {
    const match = pattern.exec(text)
    if (match?.[1]) return match[1].trim()
  }
  return fallback
}

export function stripMd(value) {
  return value
    .replace(/^#+\s*/, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/\s+/g, ' ')
    .trim()
}

// 解析 README 顶部的 YAML frontmatter，返回对象。只处理简单标量（字符串/布尔/数字），不引入外部 YAML 依赖。
export function parseFrontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n?/)
  if (!match) return {}
  const result = {}
  for (const line of match[1].split('\n')) {
    const colonIndex = line.indexOf(':')
    if (colonIndex === -1) continue
    const key = line.slice(0, colonIndex).trim()
    let value = line.slice(colonIndex + 1).trim()
    let quoted = false
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
      quoted = true
    }
    if (value === 'true') result[key] = true
    else if (value === 'false') result[key] = false
    else if (!quoted && /^\d+$/.test(value)) result[key] = Number(value)
    else result[key] = value
  }
  return result
}

export function frontmatterStatus(readme) {
  const fm = parseFrontmatter(readme)
  if (fm.stage) return `${fm.stage}`
  if (fm.status && fm.status !== 'active') return `${fm.status}`
  return ''
}

// 只取表格机器行「最新通过门禁」。它是 set-project-stage.mjs 的唯一写真值，优先级高于 frontmatter。
export function machineRowStatus(readme) {
  return stripMd(firstMatch(readme, [/\|\s*(?:\*\*)?最新通过门禁(?:\*\*)?\s*\|\s*([^|]+)\|/], ''))
}

// README 状态解析：机器行「最新通过门禁」优先（gate 通过时脚本写入，客观真值）；人工叙述行只做回落。
export function parseStatus(readme) {
  return stripMd(firstMatch(readme, [
    /\|\s*(?:\*\*)?最新通过门禁(?:\*\*)?\s*\|\s*([^|]+)\|/,
    /^>\s*\*\*状态\*\*[:：]\s*(.+)$/m,
    /^>\s*状态[:：]\s*(.+)$/m,
    /\|\s*(?:\*\*)?当前阶段(?:\*\*)?\s*\|\s*([^|]+)\|/,
    /\|\s*(?:\*\*)?代码实现(?:\*\*)?\s*\|\s*([^|]+)\|/,
  ], '未记录'))
}

// 阶段真值分级：README 声称的 stage 若没有同阶段真实 PASS 历史就打标，避免「自己写上去的阶段」
// 和「机器背书的阶段」在索引里长得一样。G5+ 沿用历史标记 legacy-unverified（多为机制上线前的旧项目），
// G2-G4 用 self-declared（gate 早已可跑，没跑就是没跑）。G0/G1 不打标：按 workflow-gates，
// 项目 gate 从 G2 起才要求逐阶段跑，G0/G1 本就没有「应存在的 PASS」。
const SELF_DECLARED_STAGES = ['G2', 'G3', 'G4']

export function legacyAwareStatus(status, history, evidenceExists) {
  const stage = String(status || '').match(/\b(G[2-8])\b/)?.[1]
  if (!stage) return status
  const marker = SELF_DECLARED_STAGES.includes(stage) ? 'self-declared' : 'legacy-unverified'
  if (String(status).includes(marker)) return status
  const verified = Array.isArray(history?.runs) && history.runs.some((run) => (
    run?.gate === stage
    && run?.ok === true
    && run?.summary?.fail === 0
    && typeof run?.evidence === 'string'
    && evidenceExists(run.evidence)
  ))
  return verified ? status : `${status} (${marker})`
}

// 若 G5 记为报告态 frontend-complete-pending-reconcile（前端完成、仅待真实字段对账），追加可读标记。
export function frontendReconcileNote(status, stageStatusJson) {
  const g5 = stageStatusJson?.stages?.G5?.status
  if (g5 !== 'frontend-complete-pending-reconcile') return status
  return String(status).includes('前端完成待对账') ? status : `${status} · 前端完成待对账`
}

function cell(value) {
  return String(value || '未记录').replace(/\|/g, '\\|').replace(/\n/g, '<br>')
}

function worktreeCell(project) {
  if (!project.worktree) return '—（无活跃 worktree）'
  return `\`${project.worktree}\``
}

export function renderMarkdown(projects, generatedAt) {
  const rows = projects.map((project) => `| [${cell(project.id)}](./prds/${cell(project.id)}/README.md) | ${cell(project.status)} | ${cell(project.g2)} | ${cell(project.gate)} | ${project.evidenceCount} | ${worktreeCell(project)} | ${cell(project.modulePath)} |`)
  return `# docs_tdd Project Index

> Generated by \`common/engine/agent-scripts/update-project-index.mjs --write\` at ${generatedAt}. Do not hand-edit table rows; update project README / product docs, then regenerate.
> 本表是「当前有哪些项目 / 状态 / 在哪个 worktree」的唯一生成式聚合视图，不是底层事实源。Worktree 列直接派生自 \`git worktree list\`，禁止手工登记；README / AGENTS / CONTEXT 只放指向本表的指针，不得再抄一份项目清单（\`check-doc-budget.mjs\` 会拦）。

## Active Projects

| Project | Status | G2 | Latest gate | Evidence files | Worktree | Responsibility modules |
|---------|--------|----|-------------|----------------|----------|-------------------------|
${rows.join('\n')}

## Notes

- This index is a generated navigation view; its underlying facts remain in each project README / agent state and Git.
- Project status uses the machine row \`| 最新通过门禁 | GX |\` first, then README frontmatter \`stage\`, then narrative rows. G2+ without matching successful gate history and existing evidence is labeled \`self-declared\` (G2-G4) or \`legacy-unverified\` (G5+).
- \`self-declared\` = README 声称到了 G2-G4，但 \`agent/gate-history.json\` 没有同阶段真实 PASS。项目 gate 从 G2 起就该逐阶段跑，没跑就是没跑；出口是补跑 \`docs-tdd gate <PR> <Gx> --write\`，不是改 README。
- \`legacy-unverified\` = 机制上线（gate-history 机器背书）之前的自声明 G8/G5+，非机器背书。这些旧项目 worktree 多已回收、无真实 gate 运行；**不 backfill 伪造 PASS 历史**（违反"不伪造证据"原则）。要转为机器背书须有真实结构的 \`agent/gate-history.json\` 且其 evidence 路径真实存在。
- \`· 前端完成待对账\` = G5 记为报告态 \`frontend-complete-pending-reconcile\`：前端已交付、仅待后端真实字段对账；此态不放行 G6（见 \`workflow-gates.md\`）。
- G2/module data comes from \`product/00-feature-inventory.md\`; final gate data comes from \`agent/gate-results.json\` when present.
- Worktree column is derived live from \`git worktree list\` (configured branch prefix or \`fix/<ID>\`); a project with no active worktree shows \`—\`.
- Regenerate after creating or materially updating a project: \`node apps/web/docs_tdd/common/engine/agent-scripts/update-project-index.mjs --write\`.
- README frontmatter schema is enforced by \`common/engine/schemas/project-frontmatter.schema.json\`; invalid frontmatter will be reported by \`check-doc-budget.mjs\`.
`
}

export function selfTest() {
  const stripped = stripMd('`apps/web/docs_tdd/prds/PR-00001` **done**')
  assert.ok(stripped.includes('docs_tdd') && !stripped.includes('`') && !stripped.includes('**'), 'stripMd should preserve underscores and remove markdown markers')
  const markdown = renderMarkdown([
    { id: 'PR-00001', status: 'G6', g2: 'Aven / 2026-07-10', gate: 'G6 PASS (fail=0, warn=0)', evidenceCount: 1, worktree: '/Users/aven/github/PR-00001', modulePath: 'apps/web/src/apps/Demo' },
  ], '2026-01-01T00:00:00.000Z')
  assert.ok(markdown.includes('[PR-00001](./prds/PR-00001/README.md)') && markdown.includes('| Project | Status |'), 'rendered markdown table is incomplete')
  assert.ok(markdown.includes('| Worktree |') && markdown.includes('/Users/aven/github/PR-00001'), 'worktree column missing from rendered table')
  const noWt = renderMarkdown([{ id: 'PR-00002', status: 'G2', g2: '—', gate: '未生成', evidenceCount: 0, worktree: '', modulePath: '—' }], '2026-01-01T00:00:00.000Z')
  assert.ok(noWt.includes('无活跃 worktree'), 'empty worktree should render placeholder')
  assert.equal(parseStatus('| 字段 | 值 |\n|------|-----|\n| 最新通过门禁 | G6 |\n| 当前阶段 | G0 资料接收 |'), 'G6', 'machine row must win over narrative 当前阶段')
  assert.equal(parseStatus('| 项 | 值 |\n|----|----|\n| **当前阶段** | **G4 开发中** |'), 'G4 开发中', 'bold 当前阶段 label should still parse')
  assert.equal(parseStatus('> **状态**: G5 联调中'), 'G5 联调中', 'quote-style status fallback broken')
  const fm = parseFrontmatter('---\nprojectId: PR-00003\nstage: G6\nstatus: active\n---\n# PR-00003')
  assert.ok(fm.projectId === 'PR-00003' && fm.stage === 'G6' && fm.status === 'active', 'parseFrontmatter should parse simple scalars')
  assert.equal(frontmatterStatus('---\nstage: G6\n---\n# PR-00003\n\n## 状态\n| 当前阶段 | G0 |'), 'G6', 'frontmatter stage must win over narrative status')
  const prioritySample = '---\nstage: G4\n---\n# PR-00004\n\n## 状态\n\n| 字段 | 值 |\n|------|-----|\n| 最新通过门禁 | G6 |\n| 当前阶段 | G0 |'
  assert.equal(machineRowStatus(prioritySample) || frontmatterStatus(prioritySample) || parseStatus(prioritySample), 'G6', 'machine row must win over frontmatter stage')
  assert.equal(legacyAwareStatus('G8', { runs: [] }, () => false), 'G8 (legacy-unverified)', 'G5+ without machine history must be marked legacy-unverified')
  assert.equal(legacyAwareStatus('G8', { runs: [{ gate: 'G8', ok: true, summary: { fail: 0 }, evidence: 'evidence/gate/g8/README.md' }] }, () => true), 'G8', 'verified G8 should not carry legacy marker')
  assert.equal(legacyAwareStatus('G4 开发中', { runs: [] }, () => false), 'G4 开发中 (self-declared)', 'G2-G4 without machine history must be marked self-declared')
  assert.equal(legacyAwareStatus('G4', { runs: [{ gate: 'G4', ok: true, summary: { fail: 0 }, evidence: 'evidence/gate/g4/README.md' }] }, () => true), 'G4', 'verified G4 should carry no marker')
  assert.equal(legacyAwareStatus('G4', { runs: [{ gate: 'G4', ok: true, summary: { fail: 0 }, evidence: 'evidence/gate/g4/README.md' }] }, () => false), 'G4 (self-declared)', 'G4 history with missing evidence file must still be marked')
  assert.equal(legacyAwareStatus('G1 资料接收', { runs: [] }, () => false), 'G1 资料接收', 'G0/G1 have no expected PASS history and must stay unmarked')
  assert.equal(legacyAwareStatus('G4 (self-declared)', { runs: [] }, () => false), 'G4 (self-declared)', 'marker must not be appended twice')
  assert.equal(frontendReconcileNote('G4', { stages: { G5: { status: 'frontend-complete-pending-reconcile' } } }), 'G4 · 前端完成待对账', 'frontend-complete-pending-reconcile G5 should annotate status')
  assert.equal(frontendReconcileNote('G4', { stages: { G5: { status: 'blocked' } } }), 'G4', 'non-reconcile G5 status must not annotate')
  console.log('PASS project index renderer')
}

if (process.argv[1] && process.argv[1].endsWith('project-index.mjs') && process.argv.includes('--self-test')) {
  selfTest()
  process.exit(0)
}
