#!/usr/bin/env node
// v3.2 extraction scaffold/apply command. Source units are generated by the CLI; callers only fill
// candidate fields. Applying a candidate always runs and persists the deterministic intake audit.

import assert from 'node:assert/strict'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { isAbsolute, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { docsSystemRoot } from './lib/roots.mjs'
import { runIntakeAudit } from './lib/vnext-intake-audit.mjs'
import { persistVNextWorkItem } from './lib/vnext-persistence.mjs'
import { normalizeSourceDocuments, readLocalSourceAsset } from './lib/vnext-source-units.mjs'
import { coverageFingerprints } from './lib/vnext-work-item.mjs'
import { EXTRACTION_GUIDANCE_V2, detectDomainSignals, formatDomainGuidance } from './lib/extraction-guidance.mjs'

const CANDIDATE_FIELDS = [
  'extractionFacts', 'requirements', 'sourceUnitDispositions', 'evidenceCommands', 'requirementsAuthor',
  'routing', 'apiDependency', 'sourceReadiness', 'deliveryScope',
]

function normalizedSources(workItem, root = docsSystemRoot) {
  const documents = (workItem.sourceSnapshot?.sources || []).map((source) => {
    const file = isAbsolute(source.path) ? source.path : resolve(root, source.path)
    if (!existsSync(file)) throw new Error(`source file is missing: ${source.path}`)
    return { path: source.path, content: readFileSync(file, 'utf8') }
  })
  return normalizeSourceDocuments(documents, {
    revision: workItem.sourceSnapshot.revision,
    readAsset: (asset) => readLocalSourceAsset(asset, { root }),
  })
}

export function scaffoldExtraction(workItem, { root = docsSystemRoot } = {}) {
  const normalized = normalizedSources(workItem, root)
  const expected = coverageFingerprints(workItem).sourceFingerprint
  const actual = coverageFingerprints({ sourceSnapshot: normalized.sourceSnapshot }).sourceFingerprint
  if (expected !== actual) throw new Error('current source/assets differ from workItem.sourceSnapshot; run docs-tdd source-sync first')

  // Detect domain signals and generate tailored guidance
  const domainSignals = detectDomainSignals(normalized.sourceUnits)
  const domainGuidance = formatDomainGuidance(domainSignals)
  const fullGuidance = EXTRACTION_GUIDANCE_V2 + domainGuidance

  return {
    schemaVersion: 1,
    projectId: workItem.projectId,
    sourceFingerprint: expected,
    extractionGuidance: fullGuidance,
    instructions: [
      'Read every semantic source unit and every readable image/table/embed before extracting.',
      'Map each semantic unit to an atomic requirement/fact, or provide exact exclusionEvidence; unresolved or unread content blocks progress.',
      'Expand collection language and sibling entry points into explicit affectedSurfaces with an exact expectedCount.',
      'Do not let passive-display or existing-logic wording suppress an explicit field, action, entry, export, filter, or other requested function.',
      'Provide focused evidenceCommands for every doing requirement and implement surface; batch checks after edits stabilize.',
    ],
    sourceUnits: normalized.sourceUnits,
    extractionFacts: workItem.extractionFacts || [],
    requirements: workItem.requirements || [],
    sourceUnitDispositions: workItem.sourceUnitDispositions || [],
    evidenceCommands: workItem.evidenceCommands || [],
    requirementsAuthor: workItem.requirementsAuthor || { kind: 'model', id: '', client: '', sessionId: '' },
    routing: workItem.routing,
    apiDependency: workItem.apiDependency,
    ...(workItem.sourceReadiness ? { sourceReadiness: workItem.sourceReadiness } : {}),
    ...(workItem.deliveryScope ? { deliveryScope: workItem.deliveryScope } : {}),
  }
}

export function applyExtractionCandidate(workItem, candidate, { root = docsSystemRoot, auditedAt } = {}) {
  if (candidate?.schemaVersion !== 1 || candidate?.projectId !== workItem.projectId) throw new Error('extraction candidate schemaVersion/projectId does not match work item')
  const scaffold = scaffoldExtraction(workItem, { root })
  if (candidate.sourceFingerprint !== scaffold.sourceFingerprint) throw new Error('extraction candidate source fingerprint is stale; regenerate the scaffold')
  const next = structuredClone(workItem)
  for (const field of CANDIDATE_FIELDS) {
    if (Object.hasOwn(candidate, field)) next[field] = structuredClone(candidate[field])
    else if (['extractionFacts', 'requirements', 'requirementsAuthor', 'routing', 'apiDependency'].includes(field)) throw new Error(`extraction candidate requires ${field}`)
  }
  const previousFingerprints = coverageFingerprints(workItem)
  const nextFingerprints = coverageFingerprints(next)
  const scopeChanged = previousFingerprints.sourceFingerprint !== nextFingerprints.sourceFingerprint
    || previousFingerprints.requirementsFingerprint !== nextFingerprints.requirementsFingerprint
  if (scopeChanged) {
    next.coverageAudit = {
      sourceFingerprint: 'pending', requirementsFingerprint: 'pending', reviewMode: 'independent-cold-read',
      reviewRunId: 'pending', reviewer: { kind: 'model', id: 'pending' }, completedAt: '2000-01-01T00:00:00Z',
      verdict: 'changes-required', unresolved: ['deterministic intake passed; independent review is pending'],
    }
    next.scopeApproval = null
    next.reviewAdjudication = null
  }
  next.extractionAudit = runIntakeAudit(next, scaffold.sourceUnits, { ...(auditedAt ? { auditedAt } : {}) })
  return next
}

export function selfTest() {
  const root = mkdtempSync(join(tmpdir(), 'docs-tdd-extract-test-'))
  try {
    writeFileSync(join(root, 'prd.md'), '# Scope\n\nChange A.\n')
    const { sourceSnapshot, sourceUnits } = normalizeSourceDocuments([{ path: 'prd.md', content: '# Scope\n\nChange A.\n' }], { revision: '1' })
    const workItem = { workflowVersion: 2, projectId: 'PR-00001', sourceSnapshot, requirements: [], routing: { scopeClass: 'local', riskSignals: [], verificationLevel: 'V0', routerVersion: 1 }, apiDependency: { mode: 'no-request', reason: 'copy only' }, coverageAudit: {}, scopeApproval: null }
    const scaffold = scaffoldExtraction(workItem, { root })
    assert.equal(scaffold.sourceUnits.length, 2)
    const semantic = sourceUnits.find((unit) => unit.content === 'Change A.')
    const candidate = {
      ...scaffold,
      extractionFacts: [{ factId: 'F-001', category: 'action', statement: 'Change A.', sourceIds: [semantic.sourceId], requirementIds: ['R-001'] }],
      requirements: [{ requirementId: 'R-001', sourceAnchors: [{ type: 'text', sourceId: semantic.sourceId }], statement: 'Change A.', status: 'doing', collectionSemantics: { kind: 'none', expectedCount: 0 }, affectedSurfaces: [{ surfaceId: 'S-001', locator: 'src/a.ts', disposition: 'implement' }], evidencePlan: [{ type: 'copy-literal', runtimeRequired: false }] }],
      evidenceCommands: [
        { evidenceId: 'E-1', kind: 'copy-literal', argv: ['node', 'scripts/check-copy.mjs'], requirementIds: ['R-001'], surfaceIds: ['S-001'] },
        { evidenceId: 'E-2', kind: 'touched-file-quality', argv: ['pnpm', 'exec', 'biome', 'check', 'apps/web/src/a.ts'] },
      ],
      requirementsAuthor: { kind: 'model', id: 'pi/test', client: 'pi', sessionId: 'author-1' },
    }
    const applied = applyExtractionCandidate(workItem, candidate, { root, auditedAt: '2026-09-12T00:00:00Z' })
    assert.equal(applied.extractionAudit.status, 'pass', JSON.stringify(applied.extractionAudit))
    assert.equal(applied.coverageAudit.verdict, 'changes-required')
    const priorReview = { status: 'passed', attempts: 1, history: [{ verdict: 'pass' }] }
    const reviewedWorkItem = { ...applied, reviewControl: priorReview, coverageAudit: { ...applied.coverageAudit, ...coverageFingerprints(applied), verdict: 'pass', unresolved: [] } }
    const evidenceOnly = structuredClone(candidate)
    evidenceOnly.evidenceCommands[0].argv.push('--focused')
    const revised = applyExtractionCandidate(reviewedWorkItem, evidenceOnly, { root })
    assert.deepEqual(revised.reviewControl, priorReview)
    assert.equal(revised.coverageAudit.verdict, 'pass')
    assert.notEqual(revised.extractionAudit.evidencePlanFingerprint, applied.extractionAudit.evidencePlanFingerprint)
    assert.throws(() => applyExtractionCandidate(workItem, { ...candidate, sourceFingerprint: 'stale' }, { root }), /stale/)
    console.log('vnext-extract self-test passed')
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
}

function argumentValue(flag) {
  const index = process.argv.indexOf(flag)
  return index < 0 ? '' : process.argv[index + 1] || ''
}

/**
 * Generate a user-friendly understanding summary for quick confirmation (10 seconds).
 * @param {object} workItem - The work item after extraction
 * @returns {string} Formatted summary text
 */
function generateUnderstandingSummary(workItem) {
  const doing = workItem.requirements?.filter((r) => r.status === 'doing') || []
  const surfaces = doing.flatMap((r) => r.affectedSurfaces || []).filter((s) => s.disposition === 'implement')
  const highRisk = workItem.routing?.riskSignals || []
  const imageRequirements = workItem.requirements?.filter((r) => r.sourceAnchors?.some((a) => a.type === 'image')) || []

  let summary = '\n【核心功能】\n'
  if (doing.length === 0) {
    summary += '- （无 doing 状态需求）\n'
  } else {
    summary += doing.slice(0, 5).map((r) => `- ${r.statement}`).join('\n')
    if (doing.length > 5) summary += `\n- ... 共 ${doing.length} 条需求\n`
  }

  summary += '\n【关键落点】\n'
  if (surfaces.length === 0) {
    summary += '- （无 implement 落点）\n'
  } else {
    summary += surfaces.slice(0, 8).map((s) => `- ${s.locator}`).join('\n')
    if (surfaces.length > 8) summary += `\n- ... 共 ${surfaces.length} 个落点\n`
  }

  if (highRisk.length > 0) {
    summary += '\n【高风险点】\n'
    summary += highRisk.map((r) => `- ${r}`).join('\n') + '\n'
  } else {
    summary += '\n【高风险点】\n- 无\n'
  }

  if (imageRequirements.length > 0) {
    summary += '\n【图片独有需求】\n'
    summary += imageRequirements.slice(0, 3).map((r) => `- ${r.statement}`).join('\n')
    if (imageRequirements.length > 3) summary += `\n- ... 共 ${imageRequirements.length} 条图片需求\n`
  }

  const collections = workItem.requirements?.filter((r) => r.collectionSemantics?.kind !== 'none' && (r.collectionSemantics?.expectedCount || 0) > 1) || []
  if (collections.length > 0) {
    summary += '\n【集合枚举】\n'
    collections.forEach((r) => {
      summary += `- ${r.statement}：${r.collectionSemantics.expectedCount} 个成员\n`
    })
  }

  return summary
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--self-test')) selfTest()
  else {
    try {
      const projectDir = resolve(argumentValue('--project'))
      const workItemFile = join(projectDir, 'work-item.json')
      const workItem = JSON.parse(readFileSync(workItemFile, 'utf8'))
      const input = argumentValue('--input')
      if (process.argv.includes('--check')) {
        const scaffold = scaffoldExtraction(workItem)
        const audit = runIntakeAudit(workItem, scaffold.sourceUnits)
        console.log(JSON.stringify(audit, null, 2))
        process.exitCode = audit.status === 'pass' ? 0 : 1
      } else if (!input) {
        const scaffold = scaffoldExtraction(workItem)
        const output = argumentValue('--out')
        if (output) writeFileSync(resolve(output), `${JSON.stringify(scaffold, null, 2)}\n`)
        else console.log(JSON.stringify(scaffold, null, 2))
      } else {
        const candidate = JSON.parse(readFileSync(resolve(input), 'utf8'))
        const next = applyExtractionCandidate(workItem, candidate)
        const persisted = persistVNextWorkItem(projectDir, next)

        // Generate understanding summary for user confirmation
        const summary = generateUnderstandingSummary(next)
        console.error('\n' + '='.repeat(60))
        console.error('需求理解摘要（请确认是否遗漏）')
        console.error('='.repeat(60))
        console.error(summary)
        console.error('='.repeat(60))
        console.error('\n请确认：✅ 理解正确 / ⚠️ 有遗漏（如有遗漏请指出）\n')

        console.log(JSON.stringify({ projectId: next.projectId, extractionAudit: next.extractionAudit, persisted }, null, 2))
        process.exitCode = next.extractionAudit.status === 'pass' ? 0 : 1
      }
    } catch (error) {
      console.error(`vNext extraction failed: ${error.message}`)
      process.exitCode = 2
    }
  }
}
