#!/usr/bin/env node
// v3.2 extraction scaffold/apply command. Source units are generated by the CLI; callers only fill
// candidate fields. Applying a candidate always runs and persists the deterministic intake audit.

import assert from 'node:assert/strict'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { isAbsolute, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { docsSystemRoot } from './lib/roots.mjs'
import { runIntakeAudit } from './lib/vnext-intake-audit.mjs'
import { persistVNextWorkItem } from './lib/vnext-persistence.mjs'
import { normalizeSourceDocuments, readLocalSourceAsset } from './lib/vnext-source-units.mjs'
import { coverageFingerprints } from './lib/vnext-work-item.mjs'

const CANDIDATE_FIELDS = [
  'extractionFacts', 'requirements', 'sourceUnitDispositions', 'evidenceCommands', 'requirementsAuthor',
  'routing', 'apiDependency', 'sourceReadiness', 'deliveryScope',
]

function normalizedSources(workItem, root = docsSystemRoot) {
  const documents = (workItem.sourceSnapshot?.sources || []).map((source) => {
    const file = isAbsolute(source.path) ? source.path : resolve(root, source.path)
    if (!existsSync(file)) throw new Error(`source file is missing: ${source.path}`)
    return { path: source.path, content: readFileSync(file, 'utf8') }
  })
  return normalizeSourceDocuments(documents, {
    revision: workItem.sourceSnapshot.revision,
    readAsset: (asset) => readLocalSourceAsset(asset, { root }),
  })
}

export function scaffoldExtraction(workItem, { root = docsSystemRoot } = {}) {
  const normalized = normalizedSources(workItem, root)
  const expected = coverageFingerprints(workItem).sourceFingerprint
  const actual = coverageFingerprints({ sourceSnapshot: normalized.sourceSnapshot }).sourceFingerprint
  if (expected !== actual) throw new Error('current source/assets differ from workItem.sourceSnapshot; run docs-tdd source-sync first')
  return {
    schemaVersion: 1,
    projectId: workItem.projectId,
    sourceFingerprint: expected,
    instructions: [
      'Stage A — facts: enumerate source-grounded actions, content, states, constraints, dependencies, permissions, navigation, errors, collections, entries, and visual facts in extractionFacts.',
      'Stage B — requirements: map every fact to one or more independently testable atomic requirements; every semantic source unit must appear in a fact or have an explicit exclusion.',
      'Stage C — surfaces: expand every doing requirement into explicit affectedSurfaces, including every member of all/every sets and symmetric sibling entry points.',
      'Anchor every requirement to the same source units as its facts, including each tableRole=row unit.',
      'Declare collectionSemantics and affectedSurfaces explicitly; collection expectedCount must equal the declared member surfaces.',
      'Provide non-trivial argv-array evidenceCommands covering every doing requirement and implement surface.',
      'Batch quality checks after the related edit set is stable; target touched files and explicit directly related test files, never a repository/package/directory-wide suite.',
      'Use Vitest only for naturally separate pure/tool-shaped .ts logic. Never add a Vitest/RTL render test for a .tsx component or extract component logic solely to make it unit-testable; prove component DOM with a Node DOM-contract script or browser evidence.',
      'For collection response parsers, include a focused pure-logic case proving one malformed field/item does not suppress the remaining valid items.',
    ],
    sourceUnits: normalized.sourceUnits,
    extractionFacts: workItem.extractionFacts || [],
    requirements: workItem.requirements || [],
    sourceUnitDispositions: workItem.sourceUnitDispositions || [],
    evidenceCommands: workItem.evidenceCommands || [],
    requirementsAuthor: workItem.requirementsAuthor || { kind: 'model', id: '', client: '', sessionId: '' },
    routing: workItem.routing,
    apiDependency: workItem.apiDependency,
    ...(workItem.sourceReadiness ? { sourceReadiness: workItem.sourceReadiness } : {}),
    ...(workItem.deliveryScope ? { deliveryScope: workItem.deliveryScope } : {}),
  }
}

export function applyExtractionCandidate(workItem, candidate, { root = docsSystemRoot, auditedAt } = {}) {
  if (candidate?.schemaVersion !== 1 || candidate?.projectId !== workItem.projectId) throw new Error('extraction candidate schemaVersion/projectId does not match work item')
  const scaffold = scaffoldExtraction(workItem, { root })
  if (candidate.sourceFingerprint !== scaffold.sourceFingerprint) throw new Error('extraction candidate source fingerprint is stale; regenerate the scaffold')
  const next = structuredClone(workItem)
  for (const field of CANDIDATE_FIELDS) {
    if (Object.hasOwn(candidate, field)) next[field] = structuredClone(candidate[field])
    else if (['extractionFacts', 'requirements', 'requirementsAuthor', 'routing', 'apiDependency'].includes(field)) throw new Error(`extraction candidate requires ${field}`)
  }
  const previousFingerprints = coverageFingerprints(workItem)
  const nextFingerprints = coverageFingerprints(next)
  const scopeChanged = previousFingerprints.sourceFingerprint !== nextFingerprints.sourceFingerprint
    || previousFingerprints.requirementsFingerprint !== nextFingerprints.requirementsFingerprint
  if (scopeChanged) {
    next.coverageAudit = {
      sourceFingerprint: 'pending', requirementsFingerprint: 'pending', reviewMode: 'independent-cold-read',
      reviewRunId: 'pending', reviewer: { kind: 'model', id: 'pending' }, completedAt: '2000-01-01T00:00:00Z',
      verdict: 'changes-required', unresolved: ['deterministic intake passed; independent review is pending'],
    }
    next.scopeApproval = null
    next.reviewAdjudication = null
  }
  next.extractionAudit = runIntakeAudit(next, scaffold.sourceUnits, { ...(auditedAt ? { auditedAt } : {}) })
  return next
}

export function selfTest() {
  const root = mkdtempSync(join(tmpdir(), 'docs-tdd-extract-test-'))
  try {
    writeFileSync(join(root, 'prd.md'), '# Scope\n\nChange A.\n')
    const { sourceSnapshot, sourceUnits } = normalizeSourceDocuments([{ path: 'prd.md', content: '# Scope\n\nChange A.\n' }], { revision: '1' })
    const workItem = { workflowVersion: 2, projectId: 'PR-00001', sourceSnapshot, requirements: [], routing: { scopeClass: 'local', riskSignals: [], verificationLevel: 'V0', routerVersion: 1 }, apiDependency: { mode: 'no-request', reason: 'copy only' }, coverageAudit: {}, scopeApproval: null }
    const scaffold = scaffoldExtraction(workItem, { root })
    assert.equal(scaffold.sourceUnits.length, 2)
    const semantic = sourceUnits.find((unit) => unit.content === 'Change A.')
    const candidate = {
      ...scaffold,
      extractionFacts: [{ factId: 'F-001', category: 'action', statement: 'Change A.', sourceIds: [semantic.sourceId], requirementIds: ['R-001'] }],
      requirements: [{ requirementId: 'R-001', sourceAnchors: [{ type: 'text', sourceId: semantic.sourceId }], statement: 'Change A.', status: 'doing', collectionSemantics: { kind: 'none', expectedCount: 0 }, affectedSurfaces: [{ surfaceId: 'S-001', locator: 'src/a.ts', disposition: 'implement' }], evidencePlan: [{ type: 'copy-literal', runtimeRequired: false }] }],
      evidenceCommands: [
        { evidenceId: 'E-1', kind: 'copy-literal', argv: ['node', 'scripts/check-copy.mjs'], requirementIds: ['R-001'], surfaceIds: ['S-001'] },
        { evidenceId: 'E-2', kind: 'touched-file-quality', argv: ['pnpm', 'exec', 'biome', 'check', 'apps/web/src/a.ts'] },
      ],
      requirementsAuthor: { kind: 'model', id: 'pi/test', client: 'pi', sessionId: 'author-1' },
    }
    const applied = applyExtractionCandidate(workItem, candidate, { root, auditedAt: '2026-09-12T00:00:00Z' })
    assert.equal(applied.extractionAudit.status, 'pass', JSON.stringify(applied.extractionAudit))
    assert.equal(applied.coverageAudit.verdict, 'changes-required')
    const priorReview = { status: 'passed', attempts: 1, history: [{ verdict: 'pass' }] }
    const reviewedWorkItem = { ...applied, reviewControl: priorReview, coverageAudit: { ...applied.coverageAudit, ...coverageFingerprints(applied), verdict: 'pass', unresolved: [] } }
    const evidenceOnly = structuredClone(candidate)
    evidenceOnly.evidenceCommands[0].argv.push('--focused')
    const revised = applyExtractionCandidate(reviewedWorkItem, evidenceOnly, { root })
    assert.deepEqual(revised.reviewControl, priorReview)
    assert.equal(revised.coverageAudit.verdict, 'pass')
    assert.notEqual(revised.extractionAudit.evidencePlanFingerprint, applied.extractionAudit.evidencePlanFingerprint)
    assert.throws(() => applyExtractionCandidate(workItem, { ...candidate, sourceFingerprint: 'stale' }, { root }), /stale/)
    console.log('vnext-extract self-test passed')
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
}

function argumentValue(flag) {
  const index = process.argv.indexOf(flag)
  return index < 0 ? '' : process.argv[index + 1] || ''
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--self-test')) selfTest()
  else {
    try {
      const projectDir = resolve(argumentValue('--project'))
      const workItemFile = join(projectDir, 'work-item.json')
      const workItem = JSON.parse(readFileSync(workItemFile, 'utf8'))
      const input = argumentValue('--input')
      if (process.argv.includes('--check')) {
        const scaffold = scaffoldExtraction(workItem)
        const audit = runIntakeAudit(workItem, scaffold.sourceUnits)
        console.log(JSON.stringify(audit, null, 2))
        process.exitCode = audit.status === 'pass' ? 0 : 1
      } else if (!input) {
        const scaffold = scaffoldExtraction(workItem)
        const output = argumentValue('--out')
        if (output) writeFileSync(resolve(output), `${JSON.stringify(scaffold, null, 2)}\n`)
        else console.log(JSON.stringify(scaffold, null, 2))
      } else {
        const candidate = JSON.parse(readFileSync(resolve(input), 'utf8'))
        const next = applyExtractionCandidate(workItem, candidate)
        const persisted = persistVNextWorkItem(projectDir, next)
        console.log(JSON.stringify({ projectId: next.projectId, extractionAudit: next.extractionAudit, persisted }, null, 2))
        process.exitCode = next.extractionAudit.status === 'pass' ? 0 : 1
      }
    } catch (error) {
      console.error(`vNext extraction failed: ${error.message}`)
      process.exitCode = 2
    }
  }
}
